version: '3.0'
services:
  bot:
    env_file:
    - bot.env
    depends_on:
    - redis
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  redis:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    image: "redis:alpine"